WSI_DIR: 
  SMU: /media/zbc/hanchu001/glioma/data/raw_data/南方医/已切
  TCGA: /media/zbc/hanchu001/glioma/data/raw_data/TCGA/TCGA_Glioma_DX
  GDPH: [/media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批/已挑选_muti_resolu,
          /media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/image_muti_resolu]
10X_DIR:
  SMU: /media/zbc/MyBook/glioma/data/nanfang/big_pathes/10X
  TCGA: /media/zbc/MyBook/glioma/data/TCGA/TCGA_10X
  GDPH: /media/zbc/hanchu001/glioma/data/GDPH/data/big_patches

MASK_DIR: 
  SMU: /media/zbc/MyBook/glioma/data/nanfang/10X_mask
  TCGA: /media/zbc/MyBook/glioma/data/TCGA/TCGA_10X_mask
  GDPH: /media/zbc/hanchu001/glioma/data/GDPH/data/10_mask

ATT_DIR:
  CAM:
    IDH: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att/IDH
    1p19q: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att/1p19q
    TERT: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att/TERT
    7g10l: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att/7g10l
  GRADCAM:
    IDH: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att_gradCAM/IDH
    1p19q: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att_gradCAM/1p19q
    TERT: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att_gradCAM/TERT
    7g10l: /media/zbc/M008/nanfang/code/nanfang/transMIL/pre_att_gradCAM/7g10l/0/

NUCLEI_SEG_DIR:
  TCGA: /media/zbc/MyBook/glioma_seg/data/seg_result/seg_40X
  SMU: /media/zbc/M008/nanfang_hospital/nuclei_seg
NUCLEI_FEATURE_DIR:
  SMU: /media/zbc/M008/nanfang_hospital/nuclei_feature
LABEL_PATH:
  SMU: 
    IDH: /media/zbc/MyBook/glioma/data/raw_data/nanfang-IDH.csv
    TERT: /media/zbc/MyBook/glioma/data/nanfang/label/nanfnag-tert.csv
    1p19q: /media/zbc/MyBook/glioma/data/raw_data/nanfang-1p19q.csv
    7g10l: /media/zbc/MyBook/glioma/data/raw_data/nanfang-7gain-10loss.csv
    AGE_GENDER: /media/zbc/MyBook/glioma/data/raw_data/nanfang_age_gender.csv

  TCGA: 
    TERT: /media/zbc/MyBook/glioma/data/raw_data/TCGA_TERT.csv
    1p19q: /media/zbc/MyBook/glioma/data/raw_data/TCGA_1p19q.csv
    IDH: /media/zbc/MyBook/glioma/data/raw_data/TCGA_IHD_1.csv
    7g10l: /media/zbc/MyBook/glioma/data/raw_data/TCGA#+7#-10.csv
    AGE_GENDER: /media/zbc/MyBook/glioma/data/raw_data/tcga_age_gender.csv
  GDPH:
    TERT: [/media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批TERT.csv,
          /media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/TERT.csv]
    1p19q: [/media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批1p19q.csv,
          /media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批1p19q.csv]
    IDH: [/media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批IDH.csv,
          /media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批IDH.csv]
    7g10l: [/media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批7-10.csv,
          /media/zbc/hanchu001/glioma/data/GDPH/data/Glioma/第二批7-10.csv]
  
PRED_PATH:
  TCGA:
    IDH: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/IDH/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
    TERT: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/TERT/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
    1p19q: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/1p19q/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
    7g10l: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/7g10l/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
  SMU:
    IDH: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/IDH/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
    TERT: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/TERT/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
    1p19q: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/1p19q/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
    7g10l: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/7g10l/20X_256/oriCamelyon/myTransMIL/fold0/best_auc.csv
  GDPH:
    IDH: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/IDH/20X_256/oriCamelyon/myTransMIL/fold0/GDPH_best_auc.csv
    TERT: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/TERT/20X_256/oriCamelyon/myTransMIL/fold0/GDPH_best_auc.csv
    1p19q: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/1p19q/20X_256/oriCamelyon/myTransMIL/fold0/GDPH_best_auc.csv
    7g10l: /media/zbc/M008/nanfang/code/nanfang/transMIL/logs/7g10l/20X_256/oriCamelyon/myTransMIL/fold0/GDPH_best_auc.csv


NEW_NAME:
  Area: Area
  Convex_Area: Con_area

  Eccentricity: Eccentr
  Major_Axis_Length: Major_L
  Solidity: Solidity
  Smoothness: Smooth

  H_Mean: H_Mean
  H_Median: H_Med
  H_Std: H_Std
  H_MAD: H_MAD
  H_Min: H_Min
  H_Max: H_Max
  H_Kurtosis: H_Kurt
  H_Skewness: H_Skew
  H_entropy: H_entro

  H_Haralick_2nd_moment: H_Ha_2m
  H_Haralick_contrast: H_Ha_con
  H_Haralick_correlation: H_Ha_cor

  Nuclei_density: N_dens

FEA_COLOR:
  Area: limegreen
  Convex_Area: limegreen

  Eccentricity: orangered
  Major_Axis_Length: orangered
  Solidity: orangered
  Smoothness: orangered

  H_Mean: royalblue
  H_Median: royalblue
  H_Std: royalblue
  H_MAD: royalblue
  H_Min: royalblue
  H_Max: royalblue
  H_Kurtosis: royalblue
  H_Skewness: royalblue
  H_entropy: royalblue

  H_Haralick_2nd_moment: orange
  H_Haralick_contrast: orange
  H_Haralick_correlation: orange

  Nuclei_density: c

GEN_EVEN:
  IDH: 
    POS: IDH Mutant
    NEG: IDH Wild
  TERT: 
    POS: TERT Mutant
    NEG: TERT Wild
  1p19q: 
    POS: codel
    NEG: non-codel
  7g10l:
    POS: Gain chr 7 & loss chr 10
    NEG: No combined CNA

GEN_LABEL:
  IDH: 
    TCGA: 
      POSITIVE: Mutant
      NEGATIVE: WT
    SMU: 
      POSITIVE: Mutant
      NEGATIVE: WT
  1p19q: 
    TCGA: 
      POSITIVE: codel
      NEGATIVE: non-codel
    SMU: 
      POSITIVE: codel
      NEGATIVE: non-codel
  TERT:
    TCGA: 
      POSITIVE: Mutant
      NEGATIVE: WT
    SMU: 
  7g10l: 
    TCGA: 
      POSITIVE: 'Gain chr 7 & loss chr 10'
      NEGATIVE: No combined CNA
    SMU: 
      POSITIVE: '1'
      NEGATIVE: '0'

HANDCRAFT_FEA_DIR: 

NEW_LABEL: 
  SMU: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/data/new_label/new_smu.csv
  TCGA: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/data/new_label/new_tcga.csv
