# Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
# H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
# H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
# Smoothness,Nuclei_density
INTER_STRIDE: 2.5
INTRA_STRIDE: 4
BOX_WIDTH: 2
Y_TICKS: [0, 0.5, 1]
Y_START: 1
START_SIZE: 8
TOP_N: 100
BACKGROUNG_COLOR: False
DATASET: SMU # SMU TCGA
GEN: 1p19q # IDH TERT 1p19q 7g10l
SAVE_DIR: /media/zbc/MyBook/glioma/code/nanfang/transMIL/figure/box_nuclei_fea

SELECTED_FEA:
  IDH: 
    TCGA: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
      H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
      H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
      Smoothness,Nuclei_density]
    SMU: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
      H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
      H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
      Smoothness,Nuclei_density]
  1p19q: 
    TCGA: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
      H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
      H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
      Smoothness,Nuclei_density]
    SMU: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
        H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
        H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
        Smoothness,Nuclei_density]
  TERT:
    TCGA: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
      H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
      H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
      Smoothness,Nuclei_density]
    SMU: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
      H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
      H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
      Smoothness,Nuclei_density]
  7g10l: 
    TCGA: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
      H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
      H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
      Smoothness,Nuclei_density]
    SMU: 
      [Area, Convex_Area,Eccentricity,Major_Axis_Length,Solidity,
      H_Mean,H_Median,H_Std,H_MAD,H_Min,H_Max,H_Kurtosis,H_Skewness,
      H_entropy,H_Haralick_2nd_moment,H_Haralick_contrast,H_Haralick_correlation,
      Smoothness,Nuclei_density]
LABEL:
  IDH: 
    TCGA: 
      POSITIVE: 'IDH Mutant'
      NEGATIVE: 'IDH Wild'
    SMU: 
  1p19q: 
    TCGA: 
    SMU: 
  TERT:
    TCGA: 
    SMU: 
  7g10l: 
    TCGA: 
    SMU: 
BOX_CONF:
  IDH: 
    TCGA: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1
    SMU: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1
  1p19q: 
    TCGA: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1
    SMU: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1
  TERT:
    TCGA: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1
    SMU: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1
  7g10l: 
    TCGA: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1
    SMU: 
      box_l_w: 0.5
      marker_s: 0.5
      tick_s: 8
      ax_l_w: 1.5
      p_x_stride: 1

SMALL_BOX_CONF:
  position: [1,1.8]
  b_width: 0.5
  b_line_w: 2
  Y_TICKS:
    TCGA: 
      IDH: 
        Area: [0, 800]
        Major_Axis_Length: [0, 45]
        H_Haralick_contrast: [0, 70]
        H_entropy: [6, 9.5]
      TERT: 
      1p19q: 
        Area: [0, 800]
        H_Median: [0, 0.15]
        H_Haralick_2nd_moment: [0, 0.19]
        Nuclei_density: [0, 300]
        H_entropy: [6, 9.3]
      7g10l:
    SMU: 
      1p19q: 
        Solidity: [1.25, 1.42]
        Eccentricity: [0.55, 0.8]

