TOP_N: 100
DATASET: SMU # SMU TCGA GDPH
GEN: 7g10l # IDH TERT 1p19q 7g10l
SAVE_DIR: /media/zbc/MyBook/glioma/code/nanfang/transMIL/figure/chord
HIGHT_TOP_K: 5
HIGHLIGHT: True
FEA_FILE_NAME:
    1p19q:
      TCGA: 1P19Q_TCGA
      SMU: 1P19Q_SMU
    TERT:
      TCGA: TERT_TCGA
      # SMU: TERT_TCGA
    IDH:
      TCGA: IDH_TCGA
      SMU: IDH_SMU
    7g10l:
      TCGA: 710_TCGA
      # SMU: 710_SMU
