DATASET: SMU # SMU TCGA
TOP_N: 100
GEN: 7g10l # IDH TERT 1p19q 7g10l
ATT_MOD: GRADCAM # GRADCAM CAM
SAVE_DIR: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/heatmap
COMBINE_SAVE_DIR: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/heatmap_combine
VOLCANO_DIR: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/volcano
COMBINE_VOLCANO_DIR: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/volcano_combine

TSNE_DIR: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/TSNE
LABEL_SIZE: 7
RELATED_DIR: /media/zbc/M008/nanfang/code/nanfang/transMIL/figure/data/related
START_SIZE:
    1p19q: 60
    TERT: 150
    IDH: 40
    7g10l: 40
OTHER_SIZE:
    1p19q: 15
    TERT: 70
    IDH: 20
    7g10l: 20

ANNO_COLOR:
  POS: mediumslateblue
  NEG: violet

VOLCANO_CONF:
  x_cut:
    1p19q:
      TCGA: .5
      SMU: .25
    TERT:
      TCGA: .25
      SMU: .25
    IDH:
      TCGA: 1
      SMU: .25
    7g10l:
      TCGA: 1
      SMU: .25
  combine_x_cut:
    1p19q: .5

    TERT: .25
    IDH: 0.5
    7g10l: 1
# 自定义每个特征的最大值
MAX_DEFINE: 
    1p19q:
      H_Mean: 0.15
      H_Median: 0.13
      H_Std: 0.1
      H_MAD: 0.06
      H_Max: 0.8
      H_Kurtosis: 2
      H_Skewness: .5
      H_Haralick_contrast: 100
      H_Haralick_2nd_moment: 0.1

