DATASET: SMU # SMU TCGA GDPH
GEN: 1p19q # IDH TERT 1p19q 7g10l
HORIZONTAL: False
SAVE_DIR: /media/zbc/MyBook/glioma/code/nanfang/transMIL/figure/horizontal_hist
X_SIZE: 8


TICKS:
  IDH: 
    TCGA: 
      X_TICKS: [-0.6,-0.3,0,0.35,0.7]
    SMU: 
      X_TICKS: [-0.7,-0.35,0,0.25,0.5]
  1p19q: 
    TCGA: 
      X_TICKS: [-0.3,-0.15,0,0.15,0.35]
    SMU: 
      X_TICKS: [-0.4,-0.2,0,0.15,0.3]
  TERT:
    TCGA: 
      X_TICKS: [-0.2,-0.1,0,0.15,0.3]
    SMU: 
      X_TICKS: [-0.3,-0.15,0,0.15,0.3]
  7g10l: 
    TCGA: 
      X_TICKS: [-0.6,-0.3,0,0.2,0.4]
    SMU: 
      X_TICKS: [-0.5,-0.25,0,0.25,0.5]
